INSERT INTO monster_type(type_name) VALUES ('Aqua');
INSERT INTO monster_type(type_name) VALUES ('Beast');
INSERT INTO monster_type(type_name) VALUES ('Beast-Warrior');
INSERT INTO monster_type(type_name) VALUES ('Dinosaur');
INSERT INTO monster_type(type_name) VALUES ('Dragon');
INSERT INTO monster_type(type_name) VALUES ('Fairy');
INSERT INTO monster_type(type_name) VALUES ('Fiend');
INSERT INTO monster_type(type_name) VALUES ('Fish');
INSERT INTO monster_type(type_name) VALUES ('Insect');
INSERT INTO monster_type(type_name) VALUES ('Machine');
INSERT INTO monster_type(type_name) VALUES ('Plant');
INSERT INTO monster_type(type_name) VALUES ('Pyro');
INSERT INTO monster_type(type_name) VALUES ('Reptile');
INSERT INTO monster_type(type_name) VALUES ('Rock');
INSERT INTO monster_type(type_name) VALUES ('Sea Serpent');
INSERT INTO monster_type(type_name) VALUES ('Spellcaster');
INSERT INTO monster_type(type_name) VALUES ('Thunder');
INSERT INTO monster_type(type_name) VALUES ('Warrior');
INSERT INTO monster_type(type_name) VALUES ('Winged Beast');
INSERT INTO monster_type(type_name) VALUES ('Zombie');